CREATE TABLE COPA_2026(
ID BIGINT GENERATED ALWAYS AS IDENTITY UNIQUE, 
PAIS TEXT,
PONTUACAO INT,
ARTILHEIRO VARCHAR(20)
);
--CHAVE PRIMÁRIA É --
--CHAVE ESTRANGEIRA É QUANDO --
--NO VARCHAR, VOCÊ DELIMITE A QUANTIDADE DE CARACTERES--
--DENTRO DELE, VOCÊ COLOCA O LIMITE DE CARACTERES--
